#!/usr/bin/python3

import cgi
import os
import configparser
from urllib.request import Request,urlopen
import json


maasconf = configparser.RawConfigParser()
maasconf.read('/app/maas/conf/env')

api_url = maasconf['api']['url']

print("Content-Type:text/html\n")
print("<html><head><link rel='stylesheet' type='text/css' href='/dark.css'></head>")
print("<h1>Monitoring Admin Tasks</h1>")
print("<hr>")

def run_cmd(command):
  try :
    result = os.popen(command)
    output = result.read().replace("\n","<BR>")
    print("Executed " + command + "<BR>")
    print("Results<BR><font face=courier>" + output)
  except:
    print("Error running " + command)

  return


fs = cgi.FieldStorage()
if 'cmd' in fs :
  cmd = fs['cmd'].value
  command = ""

  if cmd == "delete-metrics" :
    if 'entity' in fs:
      command = maasconf['influxdb']['binary'] + ' -database "telegraf" -execute "DROP SERIES WHERE host=\'%s\'"' % ( fs['entity'].value)
      run_cmd(command)

  elif cmd == "delete-entity" :
    # usage : ?cmd=delete-entity&entity=<xxx>&admin=admin
    if 'entity' in fs:
      entity = fs['entity'].value
      admin = fs['admin'].value
      params = { "entity" : entity, "admin":admin }
      data = str(json.dumps(params)).encode("utf-8")
      req = Request(api_url + "/admin/delete_entity",data=data)
      req.add_header('Content-Type','application/json')
      resp = str(urlopen(req).read(),'utf-8')
      print("Delete Entity results below <BR>")
      print(resp)

else : 
  f = open("/app/maas/html/admin","r")
  print(f.read())



