#!/usr/bin/python3

# This routing controls viewing and setting of alerting
import cgi
import glob
import subprocess
import os
import elasticsearch
import datetime
import configparser

maas = configparser.RawConfigParser()
maas.read('/app/maas/conf/env')

print("Content-Type:text/html;\n")
print("<html><head><link rel='stylesheet' type='text/css' href='/dark.css'></head>")
print("<h1><A style='text-decoration:none' HREF='/cgi-bin/index'>Monitoring Alert Management</a></h1>")
print("<hr>")

es = { "url": maas['elastic']['url'] ,"user": maas['elastic']['user'],"pass": maas['elastic']['pass'] }
entity_config_index = "maas_config_entity_publish"
alert_config_index = "maas_config_alert"

# Pull in URL parameters
fs = cgi.FieldStorage()
try:
  mode = fs['mode'].value
except:
  mode = "view"

# Routine to print a Select block with a preselected option if a match found
def print_select(id,name,options,match) :
  print("<select id='%s' name='%s'>" % (id,name))
  for option in options.split(",") :
    print("<option value='%s'" % ( option ))
    if option == match :
      print(" selected ")
    print(">%s</option>" % (option))

########### EDIT
if mode == "edit":
  # We have passed in the contents and entity so we will just set them 
  # Note : "edit=true" means don't write the detail but pre-populate form (next section)
  if 'entity' in fs and not 'edit' in fs :
    entity = fs['entity'].value
    metric_type = fs['metric_type'].value
    metric_instance = fs['metric_instance'].value
    metric_value = fs['metric_value'].value
    metric_name = fs['metric_name'].value
    alert_operator = fs['alert_operator'].value
    alert_threshold = fs['alert_threshold'].value
    support_team = fs['support_team'].value
    try:
      alert_tag = fs['alert_tag'].value
    except:
      alert_tag = ""

    key = "%s:%s:%s:%s:%s" % ( entity,metric_type,metric_instance,metric_value,metric_name )
    now = datetime.datetime.now().strftime("%d/%m/%Y %H:%M:%S")

    doc = { "entity":entity, "metric_type":metric_type, "metric_instance":metric_instance,"metric_value":metric_value,"metric_name":metric_name,"alert_operator":alert_operator,"alert_threshold":alert_threshold,"support_team":support_team,"alert_tag":alert_tag,"last_updated":now }
    # Open alert config
    print("<h4><font color='Red'>** Alert Written to Database **</font></h4>")
    key = key.replace("/","%2F")
    x = elasticsearch.post_document(es,alert_config_index,"_doc",key,doc)

    # print link to config
    print("<h2><A HREF='/cgi-bin/alert?mode=view'>View all Alert Configuration</A></h2>")
     
  # Either some detail was missing, or we want to go into form "edit" mode
  else :
    # See if we can get some details from the URL params
    if 'entity' in fs : 
      entity = fs['entity'].value
    else :
      entity = ""
    if 'metric_type' in fs : 
      metric_type = fs['metric_type'].value
    else :
      metric_type = ""
    if 'metric_instance' in fs : 
      metric_instance = fs['metric_instance'].value
    else :
      metric_instance = ""
    if 'metric_value' in fs : 
      metric_value = fs['metric_value'].value
    else :
      metric_value = ""
    if 'metric_name' in fs : 
      metric_name = fs['metric_name'].value
    else :
      metric_name = ""
    if 'alert_operator' in fs : 
      alert_operator = fs['alert_operator'].value
    else :
      alert_operator = ""
    if 'alert_threshold' in fs : 
      alert_threshold = fs['alert_threshold'].value
    else :
      alert_threshold = ""
    if 'support_team' in fs : 
      support_team = fs['support_team'].value
    else :
      support_team = ""
    if 'alert_tag' in fs : 
      alert_tag = fs['alert_tag'].value
    else :
      alert_tag = ""

    # Now lets build the form, populating values if we have them
    print("""
<html>
<h2>Configure metric collection for an entity </h2>
<FORM ACTION="/cgi-bin/alert?mode=edit" METHOD="POST">
<TABLE>
 <TR>
  <TD>Hostname</TD>
  <TD>
    """)
    # Build list of entities based on entitys that are currently configured
    x = elasticsearch.run_search_uri(es,entity_config_index,"q=*&size=10000")['hits']
    records = x['hits']
    entities = ""
    for record in records:
      entities += record['_source']['entity'] + ","
    entities = entities[:-1]
    print_select("entity","entity",entities,entity)
       
    print("""

  </TD>
 </TR>
 <TR>
  <TD>Metric Type</TD>
  <TD>
  """)
    print_select("metric_type","metric_type","cpu,disk,procstat,procstat_lookup,http",metric_type)
    print("""
  </TD>
 </TR>
 <TR>
  <TD>Metric Value</TD>
  <TD>
  """)
    print("<input name='metric_value' id='metric_value' value='" + metric_value + "'>")
    print("""
    </input>
  </TD>
 </TR>
 <TR>
  <TD>Metric Instance</TD>
  <TD>
  """)
    print("<input name='metric_instance' id='metric_instance' value='" + metric_instance + "'>")
    print("""
    </input>
  </TD>
 </TR>
 <TR>
  <TD>Metric Name</TD>
  <TD>
  """)
    print("<input name='metric_name' id='metric_name' value='" + metric_name + "'>")
    print("""
    </input>
  </TD>
 </TR>
 <TR>
  <TD>Alert Operator</TD>
  <TD>
  """)
    print_select("alert_operator","alert_operator","<,<=,>,<=,=",alert_operator)
    print("""
  </TD>
 </TR>
 <TR>
  <TD>Alert Threshold</TD>
  <TD>
  """)
    print("<input name='alert_threshold' id='alert_threshold' value='" + alert_threshold+ "'>")
    print("""
    </input>
  </TD>
 </TR>
 <TR>
  <TD>Support Queue</TD>
  <TD>
  """)
    print("<input name='support_team' id='support_team' value='" + support_team + "'>")
    print("""
    </input>
  </TD>
 </TR>
 <TR>
  <TD>Tag (Optional)</TD>
  <TD>
  """)
    print("<input name='alert_tag' id='alert_tag' value='" + alert_tag + "'>")
    print("""
    </input>
  </TD>
 </TR>
 <TR>
  <TD COLSPAN=2 ALIGN=CENTER>
   <input class="form-submit-button" type="submit"></input>
  </TD>
 </TR>
  
</TABLE>
</FORM>

<B>Example Metric</B><BR>
<TABLE border=1><TR><TH>Metric Type<TH>Metric Value<TH>Metric Instance<TH>Metric Name</TR>
<TR><TD>cpu<TD>cpu<TD>cpu-total<TD>usage_idle<BR>usage_system<BR>usage_user</TR>
<TR><TD>disk<TD>path<TD>/opt<BR>C:<TD>free<BR>inodes_free<BR>used<BR>used_percent</TR>
<TR><TD>procstat<TD>exe<TD>sshd<BR>syslogd<TD>cpu_time_idle<BR>cpu_time_user<BR>cpu_time_system<BR>memory_usage<BR>num_threads</TR>
<TR><TD>procstat_lookup<TD>exe<TD>sshd<BR>syslogd<TD>pid_count<BR>runnning</TR>
<TR><TD>http<TD>server<TD>http://1.2.3.4/index.html<TD>response_time<BR>result_code</TR>
</TABLE>
""")

################### VIEW Alert config
elif mode == "view":
  print("<h2>Alert Config View</h2>")
  # Alert configuration
  x = elasticsearch.run_search_uri(es,alert_config_index,"q=*&size=10000")['hits']
  alerts = x['hits']

  print("<TABLE class='blueTable'><TR><TH>Host<TH>Type<TH>Metric Value<TH>Metric Instance<TH>Metric Name<TH>Alert Operator<TH>Alert Threshold<TH>Support Team<TH>Alert Tag</TR>")

  for r in alerts:
    r = r['_source']
    entity = r['entity']
    metric_type = r['metric_type']
    metric_instance = r['metric_instance']
    metric_value = r['metric_value']
    metric_name = r['metric_name']
    alert_operator = r['alert_operator']
    alert_threshold = r['alert_threshold']
    support_team = r['support_team']
    try :
      alert_tag = r['alert_tag']
    except:
      alert_tag = ""

    params = "&entity=%s&metric_type=%s&metric_instance=%s&metric_value=%s&metric_name=%s&alert_operator=%s&alert_threshold=%s&support_team=%s&alert_tag=%s&edit=true" % ( entity,metric_type,metric_instance,metric_value,metric_name,alert_operator,alert_threshold,support_team,alert_tag)
    url = "/cgi-bin/alert?" 
    print("<TR><TD>%s<TD>%s<TD>%s<TD>%s<TD>%s<TD>%s<TD>%s<TD>%s<TD>%s<TD><A HREF='%s'>Edit</A><TD><A HREF='%s'>Delete</A></TR>" % ( entity,metric_type,metric_instance,metric_value,metric_name,alert_operator,alert_threshold,support_team,alert_tag,url + "mode=edit" + params, url + "mode=delete" + params))
  print("</TABLE>")
  print("<h3><A HREF='/cgi-bin/alert?mode=edit'>Add New Alert</A></h3>")

elif mode == "delete" :
  entity = fs['entity'].value
  metric_type = fs['metric_type'].value
  metric_instance = fs['metric_instance'].value
  metric_value = fs['metric_value'].value
  metric_name = fs['metric_name'].value
  alert_operator = fs['alert_operator'].value
  alert_threshold = fs['alert_threshold'].value
  support_team = fs['support_team'].value
  try:
    alert_tag = fs['alert_tag'].value
  except:
    alert_tag = ""

  key = "%s:%s:%s:%s:%s" % ( entity,metric_type,metric_instance,metric_value,metric_name )
  now = datetime.datetime.now().strftime("%d/%m/%Y %H:%M:%S")

  # Open alert config
  print("<h4><font color='Red'>** Alert Deleted from Database **</font></h4>")
  key = key.replace("/","%2F")
  x = elasticsearch.delete_document_by_id(es,alert_config_index,"_doc",key)
  print("<h3><A HREF='/cgi-bin/alert?mode=view'>View Alert Configuration</A></H3>")

print("</html>")

