#!/usr/bin/python3

import cgi
import glob
import urllib.request
import elasticsearch
import datetime
import configparser

maas = configparser.RawConfigParser()
maas.read('/app/maas/conf/env')

print("Content-Type:text/html;\n")
print("<html><head><link rel='stylesheet' type='text/css' href='/dark.css'></head>")
print("<h1><A style='text-decoration:none' HREF='/cgi-bin/index'>Host Monitoring Configuration Management</a></h1>")
print("<hr>")

es = { "url":maas['elastic']['url'], "user":maas['elastic']['user'], "pass":maas['elastic']['pass'] }

entity_config_index_in = "maas_config_entity_require"
entity_config_index_out = "maas_config_entity_publish"

fs = cgi.FieldStorage()
try:
  mode = fs['mode'].value
except:
  mode = "view"

########### EDIT
if mode == "edit":
  # If we have a entityname and config, then write the config out
  if 'content' in fs and 'entity' in fs :
    entity = fs['entity'].value
    content = fs['content'].value
    platform = elasticsearch.get_document_by_id(es,entity_config_index_out,"_doc",entity)['_source']['platform']
    now = datetime.datetime.now().strftime("%d/%m/%Y %H:%M:%S")
    doc = {"entity":entity,"config":content,"platform":platform,"last_updated":now}
    x = elasticsearch.post_document(es,entity_config_index_in,"_doc",entity,doc) 

    urllib.request.urlopen(maas['maas']['url'] + "/cgi-bin/telegraf-configure?host=" + entity + "&reset=true")
    print("<h2>Config written, view <A HREF='/cgi-bin/collect?mode=view&entity=" + entity + "'>here</A></h2>")
    print("<h5>Agent needes to be retarted to pick up new config</h5>")
    print("<h3>Click <A HREF='/cgi-bin/telegraf-configure?host=" + entity + "'>here</A> to see Telgraf config</h3>")
  # Only a entity passed, so try and read existing config and then show form
  elif 'entity' in fs :
    entity = fs['entity'].value
    try :
      doc = elasticsearch.get_document_by_id(es,entity_config_index_in,"_doc",entity)
      content = doc['_source']['config']
    except :
      content = ""

    print("""
<html>
Configure metric collection for a entity
<FORM ACTION="/cgi-bin/collect?mode=edit" METHOD="POST">
<TABLE>
 <TR>
  <TD>Hostname</TD>
  <TD>
    <input name="entity" id="entity" value=""" + entity + """></input>
  </TD>
  <TD>&nbsp;&nbsp;&nbsp;</TD>
  <TD> </TD>
 </TR>
 <TR>
  <TD>Content</TD>
  <TD>
    <textarea rows=10 cols=40 id="content" name="content">""" + content + """</textarea>
  </TD>
  <TD></TD>
  <TD align=center>
<B>Supported Monitors</B><BR>
process=<I>process_name</I><BR>
filesystem=<I>mount_point</I><BR>
http=<I>url</I><BR>
template=<I>pre-configure-component-template</I><BR>
  </TD>
 </TR>
 <TR>
  <TD COLSPAN=2 ALIGN=CENTER>
   <input type="submit"></input>
  </TD>
 </TR>
  

</TABLE>

</FORM>
<BR><BR>

""")
      # No fields passed so show inventory of existing entitys
  else :
    print("<h2>Monitored Host Inventory</h2>")
    print("<TABLE class='blueTable'><TR><TH>Host<TH>Action</TR>")
    try : 
      x = elasticsearch.run_search_uri(es,entity_config_index_out,"q=*&size=10000")['hits']
      records = x['hits']
    except :
      records = {}
    for r in records:
      entity = r['_source']['entity'] 
      print("<TR><TD>" + entity + "<TD><A HREF='/cgi-bin/collect?entity=" + entity + "&mode=edit'>Edit Config</A></TR>")
    print("</TABLE>")

   
#################### VIEW
elif mode == "view":
  if "entity" in fs: 
    entity = fs['entity'].value
    try:
      conf = elasticsearch.get_document_by_id(es,entity_config_index_in,"_doc",entity)['_source']['config'].split()

      print("<h2>Showing custom collection for entity " + entity + "</h2>")
      print("<TABLE class='blueTable'><TR><TH>Monitor Type</TH><TH>Instance</TH></TR>")
      for line in conf:
        x = line.split("=")
        print("<TR><TD>" + x[0] + "</TD><TD>" + x[1] + "</TD></TR>")
      print("</TABLE>")
      print("<h3><A HREF='/cgi-bin/collect?mode=edit&entity=" + entity + "'>Edit Custom Config</A></h3>")
      print("<h3><A HREF='/cgi-bin/telegraf-configure?host=" + entity + "'>View Full Config</A></h3>")
    except:
      print("<h3>No Custom Configuration found for entity %s</h3>" %  (entity))
      print("<h4><A HREF='/cgi-bin/collect?mode=edit&entity=" + entity + "'>Add New Configuration here </A></h4>")

  else :
    # Here we're going to get all entitys which have a config and display
    # in a table.  If there is a custom config, then we'll show that too
    custom = {}
    try : 
      x = elasticsearch.run_search_uri(es,entity_config_index_out,"q=*&size=10000")['hits']
      all_entitys = x['hits']
      all_entitys = sorted(all_entitys,key=lambda i: i['_source']['entity'])
      x = elasticsearch.run_search_uri(es,entity_config_index_in,"q=*&size=10000")['hits']
      custom_entitys = x['hits']
      custom_entitys = sorted(custom_entitys,key=lambda i: i['_source']['entity'])
      for r in custom_entitys:
        entity = r['_source']['entity']
        custom[entity] = True
    except :
      all_entitys = {}
    print("""
    <TABLE class='blueTable'>
    <TR><TH COLSPAN=3 ALIGN=CENTER>Configured Hosts</TH></TR>
    <TR><TH>Platform<TH>Full Config<TH>Custom Config</TR>
""")
    for r in all_entitys:
      entity = r['_source']['entity']
      platform = r['_source']['platform']
      full_url = "<A HREF='/cgi-bin/telegraf-configure?host=" + entity + "'>" + entity + "</A>"
      custom_url = "<A HREF='/cgi-bin/collect?mode=edit&entity=" + entity + "'><FONT COLOR=RED>Create New</FONT></A>"
      if entity in custom:
          custom_url = "<A HREF='/cgi-bin/collect?mode=view&entity=" + entity + "'><FONT COLOR=GREEN>View Existing</FONT></A>"
      print("<TR><TD>" + platform + "<TD ALIGN=CENTER>" + full_url + "</TD><TD>" + custom_url + "</TD></TR>")
    print("</TABLE>")
    print("<h5>Append &entity=xxx to the URL to jump directly to a entity config</h5>")
    print("<h3><A HREF='/cgi-bin/collect?mode=edit'>Add Configuration for New Host</A></h3>")
      
