#!/usr/bin/python3

import cgi
import os
import configparser

maas = configparser.RawConfigParser()
maas.read('/app/maas/conf/env')


print("Content-Type:text/html\n")
f = open("/app/maas/html/index","r")
c = f.read()
c = c.replace("%KIBANA%",maas['kibana']['url'])
c = c.replace("%CHRONOGRAF%",maas['chronograf']['url'])
c = c.replace("%GRAFANA%",maas['grafana']['url'])
c = c.replace("%PROMETHEUS%",maas['prometheus']['url'])

print(c)
