#!/usr/bin/python3

import cgi
import os
import configparser

maasconf = configparser.RawConfigParser()
maasconf.read('/app/maas/conf/env')


print("Content-Type:text/html\n")
f = open("/app/maas/html/index","r")
c = f.read()
c = c.replace("%KIBANA%",maasconf['kibana']['url'])
c = c.replace("%CHRONOGRAF%",maasconf['chronograf']['url'])
c = c.replace("%GRAFANA%",maasconf['grafana']['url'])
c = c.replace("%PROMETHEUS%",maasconf['prometheus']['url'])

print(c)
