#!/usr/bin/python3

import urllib.parse
from urllib.request import Request,urlopen
import cgi
import configparser
import json

maasconf = configparser.RawConfigParser()
maasconf.read('/app/maas/conf/env')

api_url = maasconf['api']['url']

print("Content-Type:text/html\n")
print("<html><head><link rel='stylesheet' type='text/css' href='/dark.css'></head>")
print("<h1><A style='text-decoration:none' HREF='/cgi-bin/index'>Generate Test Metrics</a></h1>")
print("<hr>")

fs = cgi.FieldStorage()
if 'entity' in fs and 'metric_name' in fs and 'metric_value' in fs and 'app_id' in fs :
  try:
    app_id = fs['app_id'].value
    entity = fs['entity'].value
    metric_name = fs['metric_name'].value
    metric_value = fs['metric_value'].value

    doc = { "entity":entity, "metric_name":metric_name, "metric_value":metric_value,"app_id":app_id }
    data = str(json.dumps(doc)).encode("utf-8")
    req = Request(api_url + "/metric/post",data=data)
    req.add_header('Content-Type','application/json')
    url = str(urlopen(req).read(),'utf-8')

    print("<h4>Metric Generated!</h4>")

    print("<h4><A HREF='%s'>View the metric here</A></H4>" % (url) )
    print("<h5>Please wait up to 1 minute for metric to appear!</h5>")
  except:
    print("<h4>Problem generating metric - please check input values")

else :
  print("<h2>Enter your custom metric details below</h2>")
  print("""
<html>
<div align="center">
<FORM ACTION="/cgi-bin/test-metric?mode=generate" METHOD="POST">
<TABLE>

 <TR>
  <TD>App Id (Numeric Only)</TD>
  <TD>
    <input name="app_id" id="app_id" pattern="[0-9]+"></input>
  </TD>
 </TR>

 <TR>
  <TD>Host Name (Lower Case)</TD>
  <TD>
    <input name="entity" id="entity" pattern="[a-z0-9\-]+"></input>
  </TD>
 </TR>

 <TR>
  <TD>Metric Name (a-z 0-9 _ -)</TD>
  <TD>
    <input name="metric_name" id="metric_name" pattern="[a-z0-9\_\-]+"></input>
  </TD>
 </TR>

 <TR>
  <TD>Metric Value (Numeric only)</TD>
  <TD>
    <input name="metric_value" id="metric_value" pattern="[0-9\.]+"></input>
  </TD>
 </TR>

 <TR>
  <TD COLSPAN=2 ALIGN=CENTER>
   <input type="submit"></input>
  </TD>
 </TR>

</TABLE>
</div>

</FORM>
""")

